import streamlit as st

st.sidebar.markdown("Developed by [Vinicius Benites](https://github.com/vinibeni2801)")

st.markdown("# Welcome to the Sales Analyzer")

st.divider()

st.markdown(
    """
    This project was developed as the final project for the course ***Python for Excel Users***.

    We will use three main libraries for its development:

    - `pandas`: for manipulating data in tables  
    - `plotly`: for generating charts  
    - `streamlit`: for creating this interactive web app that you are currently using  

    The data used was generated by the script 'gerador_de_vendas.py', which can be found alongside the project's source code. The data can be viewed in the tables tab!  
    """
)
